### ISSUE TITLE
Organize all the Files.

### ISSUE THREAD

**Issue by PraddyumnYadav** [PraddyumnYadav/PraddyumnYadavPortfolio#1]
In This Project There are Many Different Files Like Images SVG's HTML and CSS so i want Them to be totaly Organized for Example put all the images in a folder named 'images' and edit HTML File to make it working perfectly.If There are any Questions in Your Mind Dont hesistate to ask it here.

**Comment by codewithbharat** [comment]
Hey! @PraddyumnYadav I would like to do this work please assign me this task

**Comment by PraddyumnYadav** [comment]
This Bug is Already Fixed By @codewithbharat in [this](https://github.com/PraddyumnYadav/PraddyumnYadavPortfolio/pull/2#issue-1566462764) pull request.
